// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Tw95W_WH7HbHtB5EQweaBAvoeqAvtZE',
    appId: '1:826371401282:web:8d52d6005653fb408eafdb',
    messagingSenderId: '826371401282',
    projectId: 'lahack-14f69',
    authDomain: 'lahack-14f69.firebaseapp.com',
    databaseURL: 'https://lahack-14f69-default-rtdb.firebaseio.com',
    storageBucket: 'lahack-14f69.appspot.com',
    measurementId: 'G-QVCLG7NB3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChivjxq-WvHeQmSTBIbFDlN9fqrC6mjYA',
    appId: '1:826371401282:android:4a831fe84b210c478eafdb',
    messagingSenderId: '826371401282',
    projectId: 'lahack-14f69',
    databaseURL: 'https://lahack-14f69-default-rtdb.firebaseio.com',
    storageBucket: 'lahack-14f69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnj-PQakgeFtghUevw5L-IBEnmYKI228U',
    appId: '1:826371401282:ios:133546149db3f5268eafdb',
    messagingSenderId: '826371401282',
    projectId: 'lahack-14f69',
    databaseURL: 'https://lahack-14f69-default-rtdb.firebaseio.com',
    storageBucket: 'lahack-14f69.appspot.com',
    iosClientId: '826371401282-s0sb7et7a4ief6rkn008i4h84nf05o5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnj-PQakgeFtghUevw5L-IBEnmYKI228U',
    appId: '1:826371401282:ios:133546149db3f5268eafdb',
    messagingSenderId: '826371401282',
    projectId: 'lahack-14f69',
    databaseURL: 'https://lahack-14f69-default-rtdb.firebaseio.com',
    storageBucket: 'lahack-14f69.appspot.com',
    iosClientId: '826371401282-s0sb7et7a4ief6rkn008i4h84nf05o5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeAlert',
  );
}
